apiVersion: v1
kind: Secret
metadata:
  name: fleet-backend-secret
  namespace: fleet
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "fleetuser"
  SPRING_DATASOURCE_PASSWORD: "fleetpassword"
  POSTGRES_USER: "fleetuser"
  POSTGRES_PASSWORD: "fleetpassword"
  APP_JWT_SECRET: "ChangeThisSecretKeyForProdChangeThisSecretKey"
