apiVersion: v1
kind: Secret
metadata:
  name: fleet-backend-secret
  namespace: fleet
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "db2admin"
  SPRING_DATASOURCE_PASSWORD: "DBZ87ken/1987@"
  APP_JWT_SECRET: "ChangeThisSecretKeyForProdChangeThisSecretKey"
